cabal-version: 3.0
name: kyyn-surfaces
version: 0.1.0.0
license: NONE
copyright: All rights reserved.
build-type: Simple

library
  hs-source-dirs: src
  exposed-modules: Kyyn.Surfaces.Cli Kyyn.Surfaces.Result Kyyn.Surfaces.GuestApi
  default-language: GHC2021
  default-extensions: NoFieldSelectors
  ghc-options: -Wall -Werror
  build-depends: base >=4.20 && <4.21, kyyn-domain, kyyn-types, kyyn-porcelain,
    aeson, bytestring, text, optparse-applicative ==0.19.0.0

test-suite cli-arguments
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  default-language: GHC2021
  default-extensions: NoFieldSelectors
  ghc-options: -Wall -Werror
  build-depends: base >=4.20 && <4.21, kyyn-domain, kyyn-surfaces, optparse-applicative ==0.19.0.0

test-suite cli-adapters
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Adapters.hs
  default-language: GHC2021
  default-extensions: NoFieldSelectors
  ghc-options: -Wall -Werror
  build-depends: base >=4.20 && <4.21, kyyn-domain, kyyn-types, kyyn-porcelain,
    kyyn-surfaces, effectful-core ==2.6.1.0, aeson
