cabal-version: 3.0
name: kyyn-sdk
version: 0.1.0.0
license: NONE
copyright: All rights reserved.
build-type: Simple

library
  hs-source-dirs: src
  exposed-modules: Kyyn.Evolution Kyyn.Edit Kyyn.Optics
  other-modules: Kyyn.Evolution.Internal Kyyn.Edit.Internal
  default-language: Haskell2010
  ghc-options: -Wall -Werror
  build-depends: base >=4.20 && <4.21, kyyn-types, json ==0.11, transformers ==0.6.1.1

test-suite evolution-core
  type: exitcode-stdio-1.0
  main-is: EvolutionCore.hs
  hs-source-dirs: test src
  other-modules: Kyyn.Evolution Kyyn.Evolution.Internal Kyyn.Edit Kyyn.Edit.Internal Kyyn.Optics EditTests
  default-language: Haskell2010
  ghc-options: -Wall -Werror -main-is EvolutionCore.main
  build-depends: base >=4.20 && <4.21, kyyn-types, json ==0.11, transformers ==0.6.1.1
