cabal-version: 3.0
name: kyyn-porcelain
version: 0.1.0.0
license: NONE
copyright: All rights reserved.
build-type: Simple

library
  hs-source-dirs: src
  exposed-modules: Kyyn.Porcelain.Capability.RootStore
    Kyyn.Porcelain.Capability.PluginInstallation
    Kyyn.Porcelain.Capability.KnowledgeBaseInitialization
    Kyyn.Porcelain.Capability.Root
    Kyyn.Porcelain.Capability.GuestApi
    Kyyn.Porcelain.Capability.WorkspaceApi
    Kyyn.Porcelain.Capability.RootOpening
    Kyyn.Porcelain.Capability.RootPublication
    Kyyn.Porcelain.Capability.WorkspaceStore
    Kyyn.Porcelain.Capability.EvolutionStore
    Kyyn.Porcelain.Capability.EvolutionAuthoring
    Kyyn.Porcelain.Capability.EvolutionPreparation
    Kyyn.Porcelain.Capability.EvolutionReport
    Kyyn.Porcelain.Capability.EvolutionExecution
    Kyyn.Porcelain.Capability.Evolution
    Kyyn.Porcelain.Capability.RootExecution
    Kyyn.Porcelain.Capability.Validation
    Kyyn.Porcelain.Validated
    Kyyn.Porcelain.RootExecution.Types
  other-modules: Kyyn.Porcelain.Validation.Types
  default-language: GHC2021
  default-extensions: NoFieldSelectors
  ghc-options: -Wall -Werror
  build-depends: base >=4.20 && <4.21, kyyn-domain, kyyn-types, aeson, bytestring, transformers, effectful-core ==2.6.1.0
