cabal-version: 3.0
name: kyyn-plumbing
version: 0.1.0.0
license: NONE
copyright: All rights reserved for Kyyn-owned code; upstream notices remain applicable.
build-type: Simple

library
  hs-source-dirs: src
  exposed-modules: Kyyn.Plumbing.Capability.SchemaInspection.Codecs
    Kyyn.Plumbing.Capability.Failure Kyyn.Plumbing.Capability.ProcessExecution
    Kyyn.Plumbing.Capability.FileSystem Kyyn.Plumbing.Capability.GuestCompilation
    Kyyn.Plumbing.Capability.GuestCompilation.Types
    Kyyn.Plumbing.Protocol.Validation
    Kyyn.Plumbing.Protocol.Query
    Kyyn.Plumbing.Protocol.Evolution
    Kyyn.Plumbing.Protocol.EvolutionRecord
    Kyyn.Plumbing.Protocol.EvolutionRecord.Document
    Kyyn.Plumbing.Protocol.EvolutionRecord.Contract
    Kyyn.Plumbing.Capability.SchemaInspection.Metadata
    Kyyn.Plumbing.Capability.SchemaInspection
    Kyyn.Plumbing.Capability.Git
    Kyyn.Plumbing.Capability.DhallHandling
  default-language: GHC2021
  default-extensions: NoFieldSelectors OverloadedStrings
  ghc-options: -Wall -Werror
  build-depends: base >=4.20 && <4.21, kyyn-domain, bytestring, effectful-core ==2.6.1.0,
    cryptohash-sha256 ==0.11.102.1, text, kyyn-types, aeson ==2.2.5.0
